reference: 'ARS_UCD2.0.fasta'

alignment_metadata: 'alignments.csv'

targets:
  - SV
  - small

## Number of chunks to run make_examples on. More shards = more parallel.
shards: 2

## Name of the output folder
run_name: 'test'

## Impute the variants.
variant_postprocess:
  pre_filter: '-i "QUAL>=20"'
  imputation: 'beagle4'
  post_filter: '-i "D2>=0.8"'

## what regions do you want to run DeepVariant on. All is a catch-all for every contig.
regions: 'regions.bed'
PAR_regions: 'PAR.bed'

## DeepVariant model. Generally should use 'WGS'
model: 'WGS'
checkpoint: '/cluster/work/pausch/alex/REF_DATA/RNA_DV_models/model.ckpt'

#TODO: should we just hardcode the non-filter version
#TODO: update using Kishwar's change
GL_config:
  Unrevised: '/cluster/work/pausch/alex/BSW_analysis/config/GL_DV_raw.yml'
  DeepVariantWGS: ~

# DeepVariant and GLnexus containers.
