name: snakemaker
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: snakemake
        uses: snakemake/snakemake-github-action@v2
        with:
          snakemake-version: "8.28\n  - polars"
          directory: '.test'
          args: '--dryrun --configfile .test/config.yaml'
